[project]
name = "sandbox"
version = "0.1.0"
description = " C++ Sandbox System"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "mypy",
    "pyseccomp",
    "pytest",
    "ruff",
    "ty",
]


################
# Type checkers

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = "pyseccomp"
ignore_missing_imports = true

[tool.ty.rules]
all = "error"

[tool.ty.analysis]
respect-type-ignore-comments = false


#########
# Linter

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = ["CPY001", "D1", "D203", "D212"]  # missing copyright, docs, formatting docstrings

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["ERA001", "S101", "T201"]  # assert usage, print usage

[tool.ruff.lint.pylint]
max-args = 12

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
